version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zetafast_postgres
    environment:
      POSTGRES_DB: zetafast
      POSTGRES_USER: zetafast
      POSTGRES_PASSWORD: zetafast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zetafast"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 